[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
viaIR =  true
ffi = true

[rpc_endpoints]
goerli="http://3.10.105.11:8545"

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config