[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
ffi = true

[rpc_endpoints]
goerli = "https://rpc.ankr.com/eth_goerli"

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config